apiVersion: apps/v1
kind: Deployment
metadata:
  name: tri-ros2-ul-deployment
  labels:
    app: tri-ros2-ul
spec:
  selector:
    matchLabels:
      app: tri-ros2-ul
  replicas: 2
  template:
    metadata:
      labels:
        app: tri-ros2-ul
    spec:
      hostNetwork: true
      # tolerations:
      #   - effect: NoExecute
      #     key: node.kubernetes.io/unreachable
      #     operator: Exists
      #     tolerationSeconds: 2
      #   - effect: NoExecute
      #     key: node.kubernetes.io/not-ready
      #     operator: Exists
      #     tolerationSeconds: 2
      containers:
        - name: lstm-uwb
          image: 192.168.193.113:5000/tri_ros2_ul:lstm_uwb
          # yolov5_ros2:galactic-latest hello-world
          # command: ["/bin/bash", "-c"]
          # args: 
          # ["source /opt/ros/galactic/setup.bash && source /app/yolo_ws/install/setup.bash && export ROS_DOMAIN_ID=7 && ros2 run yolov5_ros2 yolo_detect --ros-args -p device:=cpu -p image_topic:=/image_raw -p model:=yolov5s"]