apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwb-lstm-deployment
  labels:
    app: uwb-lstm-deployment235
spec:
  selector:
    matchLabels:
      app: uwb-lstm-deployment235
  replicas: 1
  template:
    metadata:
      labels:
        app: uwb-lstm235
    spec:
      hostNetwork: true
      # tolerations:
      #   - effect: NoExecute
      #     key: node.kubernetes.io/unreachable
      #     operator: Exists
      #     tolerationSeconds: 2
      #   - effect: NoExecute
      #     key: node.kubernetes.io/not-ready
      #     operator: Exists
      #     tolerationSeconds: 2
      containers:
        - name: uwb_lstm235
          image: 192.168.193.113:5000/uwb-lstm-ros2core:235
          # yolov5_ros2:galactic-latest hello-world
          # command: ["/bin/bash", "-c"]
          # args: 
          # ["source /opt/ros/galactic/setup.bash && source /app/yolo_ws/install/setup.bash && export ROS_DOMAIN_ID=7 && ros2 run yolov5_ros2 yolo_detect --ros-args -p device:=cpu -p image_topic:=/image_raw -p model:=yolov5s"]